import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from '../models/Product.js';

dotenv.config();

const products = [
  { name: 'Business Starter Kit', slug: 'starter-kit', category: 'Templates', price: 999, description: 'Everything you need to launch your online presence: SEO checklist, social media calendar, 3 website templates, and 2 Python automation scripts — at 56% off individual pricing.', fileUrl: '/uploads/products/starter-kit.zip', features: ['SEO Audit Checklist (₹199 value)', 'Social Media Calendar (₹299 value)', '3 Website Templates (₹1,497 value)', '2 Python Automation Scripts (₹599 value)', 'Instant download'], originalPrice: 2594, salesCount: 88 },
  { name: 'SEO Audit Checklist', slug: 'seo-audit-checklist', category: 'Guides', price: 199, description: 'A comprehensive 50-point SEO audit checklist covering on-page, off-page, technical SEO, and local SEO.', fileUrl: '/uploads/products/seo-audit-checklist.pdf', features: ['50-point checklist', 'On-page & off-page SEO', 'Technical SEO guide', 'Local SEO section', 'Printable PDF'], salesCount: 72 },
  { name: 'Social Media Content Calendar', slug: 'social-media-calendar', category: 'Templates', price: 299, description: 'A 30-day social media content calendar template for Instagram, Facebook, LinkedIn, and Twitter.', fileUrl: '/uploads/products/social-media-calendar.xlsx', features: ['30-day calendar', 'Multi-platform support', 'Post idea prompts', 'Google Sheets format', 'Editable templates'], salesCount: 65 },
  { name: 'PC Optimization Script Bundle', slug: 'pc-optimization-scripts', category: 'Tools', price: 299, description: 'PowerShell and batch scripts to clean temp files, optimize startup, defrag drives, check disk health, and more.', fileUrl: '/uploads/products/pc-optimization-scripts.zip', features: ['10+ automation scripts', 'Clean temp files', 'Startup optimization', 'Disk health checks', 'Safe to run'], salesCount: 58 },
  { name: 'Canva Social Media Templates', slug: 'canva-social-templates', category: 'Design Assets', price: 399, description: '20 premium Canva templates for Instagram, stories, Facebook, LinkedIn, and YouTube.', fileUrl: '/uploads/products/canva-templates.zip', features: ['20 Canva templates', 'Instagram + Stories', 'Facebook + LinkedIn', 'YouTube thumbnails', 'Fully editable'], salesCount: 51 },
  { name: 'Website Template Pack', slug: 'website-template-pack', category: 'Templates', price: 499, description: '5 ready-to-use HTML/CSS website templates for portfolio, business, landing page, blog, and coming soon.', fileUrl: '/uploads/products/website-template-pack.zip', features: ['5 responsive templates', 'HTML5 + CSS3', 'Easy to customize', 'Documentation included', 'Free updates'], salesCount: 47 },
  { name: 'Python Automation Scripts', slug: 'python-automation-scripts', category: 'Tools', price: 599, description: '5 Python automation scripts for file organization, web scraping, email automation, data backup, and PDF processing.', fileUrl: '/uploads/products/python-scripts.zip', features: ['5 Python scripts', 'File organizer', 'Web scraper', 'Email automation', 'PDF tools'], salesCount: 38 },
  { name: 'Ultimate IT Support Guide', slug: 'ultimate-it-support-guide', category: 'Guides', price: 249, description: 'Step-by-step guide for Wi-Fi problems, slow PC, printer setup, email configuration, and data backup.', fileUrl: '/uploads/products/it-support-guide.pdf', features: ['50+ troubleshooting steps', 'Wi-Fi & network guide', 'PC speed optimization', 'Printer & email setup', 'Beginner friendly'], salesCount: 34 },
  { name: 'Responsive Portfolio Template', slug: 'responsive-portfolio-template', category: 'Templates', price: 799, description: 'Modern animated portfolio template with dark theme, smooth scroll, and project showcase.', fileUrl: '/uploads/products/portfolio-template.zip', features: ['Single-page portfolio', 'Dark theme', 'Smooth animations', 'Project showcase', 'Contact form ready'], salesCount: 22 },
  // --- AI Prompt Packs ---
  { name: 'SEO & Content Marketing Prompts', slug: 'prompts-seo-content', category: 'Prompt Packs', price: 199, description: '15 high-converting prompts for SEO meta descriptions, blog outlines, keyword clustering, YouTube optimization, link building, and featured snippets.', fileUrl: '/uploads/products/seo-content-prompts.md', features: ['15 SEO-optimized prompts', 'Meta description & title generators', 'Keyword clustering strategy', 'YouTube & local SEO prompts', 'E-E-A-T content booster'], salesCount: 0 },
  { name: 'Web Dev & Coding Prompts', slug: 'prompts-web-dev', category: 'Prompt Packs', price: 199, description: '15 prompts for React components, API endpoints, database schemas, Docker configs, CI/CD pipelines, debugging, and code reviews.', fileUrl: '/uploads/products/web-dev-coding-prompts.md', features: ['React & Node.js component gen', 'API endpoint & DB schema design', 'Docker & CI/CD configuration', 'Code review & debugging prompts', 'Python & TypeScript helpers'], salesCount: 0 },
  { name: 'Copywriting & Sales Prompts', slug: 'prompts-copywriting-sales', category: 'Prompt Packs', price: 199, description: '15 persuasion-engineered prompts for AIDA sales letters, email sequences, objection handling, landing pages, and VSL scripts.', fileUrl: '/uploads/products/copywriting-sales-prompts.md', features: ['AIDA sales letter framework', '5-email nurture sequences', 'Objection & price justification', 'Landing page & VSL scripts', 'Cart abandonment recovery'], salesCount: 0 },
  { name: 'Social Media Management Prompts', slug: 'prompts-social-media', category: 'Prompt Packs', price: 199, description: '15 prompts for 30-day content calendars, platform-specific captions, hashtag strategies, ad copy, and influencer outreach.', fileUrl: '/uploads/products/social-media-prompts.md', features: ['30-day content calendar gen', 'Instagram/LinkedIn/Twitter captions', 'Hashtag & ad copy strategies', 'Reel/TikTok trend adaptation', 'Influencer outreach templates'], salesCount: 0 },
  { name: 'Resume & Career Prompts', slug: 'prompts-resume-career', category: 'Prompt Packs', price: 199, description: '15 prompts for ATS-optimized resumes, cover letters, LinkedIn profiles, interview prep, salary negotiation, and career transitions.', fileUrl: '/uploads/products/resume-career-prompts.md', features: ['ATS-optimized resume builder', 'Cover letter & LinkedIn optimizer', 'STAR interview prep (10 Qs)', 'Salary negotiation scripts', 'Career transition roadmap'], salesCount: 0 },
  { name: 'Business & Startup Prompts', slug: 'prompts-business-startup', category: 'Prompt Packs', price: 299, description: '15 prompts for business model canvases, pitch decks, investor emails, market research, pricing strategy, and OKR frameworks.', fileUrl: '/uploads/products/business-startup-prompts.md', features: ['Lean Canvas & BMC generator', 'Pitch deck & investor email', 'Market research & pricing', 'OKR/KPI framework designer', 'Growth experiment engineer'], salesCount: 0 },
  { name: 'Academic & Research Prompts', slug: 'prompts-academic-research', category: 'Prompt Packs', price: 199, description: '15 prompts for literature reviews, research questions, abstracts, methodology, grant proposals, and peer review responses.', fileUrl: '/uploads/products/academic-research-prompts.md', features: ['Lit review synthesis engine', 'Research question sharpener', 'Grant proposal & abstract writer', 'Statistical analysis interpreter', 'Peer review response drafts'], salesCount: 0 },
  { name: 'Creative Writing Prompts', slug: 'prompts-creative-writing', category: 'Prompt Packs', price: 199, description: '15 prompts for story starters, character bibles, world-building, dialogue, plot twists, poetry, and flash fiction.', fileUrl: '/uploads/products/creative-writing-prompts.md', features: ['Story starter & plot twist gen', 'Character bible & world-building', 'Dialogue & scene rewriting', 'Poetry & flash fiction', 'Narrative voice shifter'], salesCount: 0 },
  { name: 'Email Marketing Prompts', slug: 'prompts-email-marketing', category: 'Prompt Packs', price: 199, description: '15 prompts for welcome sequences, abandoned cart flows, newsletters, promotional emails, A/B tests, and deliverability audits.', fileUrl: '/uploads/products/email-marketing-prompts.md', features: ['Welcome & nurture sequences', 'Abandoned cart recovery flows', 'Newsletter & promo email gen', 'A/B test experiment designer', 'Deliverability audit checker'], salesCount: 0 },
  { name: 'Productivity & Life Hacks Prompts', slug: 'prompts-productivity-life', category: 'Prompt Packs', price: 149, description: '15 prompts for time audits, GTD systems, Pomodoro optimization, habit stacking, meeting efficiency, and digital declutter.', fileUrl: '/uploads/products/productivity-life-hacks-prompts.md', features: ['Time audit & energy management', 'GTD system & weekly review', 'Habit stacking & Pomodoro', 'Meeting efficiency & workspace', 'Digital declutter & learning sprint'], salesCount: 0 },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected');
    await Product.deleteMany({});
    const created = await Product.insertMany(products);
    console.log(`Seeded ${created.length} products`);
    await mongoose.disconnect();
    console.log('Done');
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
}

seed();
